# Generated by Django 4.1.5 on 2023-01-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_f_delete_flowdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='F',
            new_name='FlowDetail',
        ),
    ]
