# Generated by Django 4.1.5 on 2023-01-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_f_flowdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowdetail',
            name='hard_timeout',
            field=models.IntegerField(max_length=128),
        ),
        migrations.AlterField(
            model_name='flowdetail',
            name='idle_timeout',
            field=models.IntegerField(max_length=128),
        ),
        migrations.AlterField(
            model_name='flowdetail',
            name='priority',
            field=models.IntegerField(max_length=128),
        ),
    ]
