# Generated by Django 4.1.5 on 2023-01-15 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_flowdetail_hard_timeout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowdetail',
            name='hard_timeout',
        ),
        migrations.RemoveField(
            model_name='flowdetail',
            name='idle_timeout',
        ),
        migrations.RemoveField(
            model_name='flowdetail',
            name='priority',
        ),
    ]
