# Generated by Django 4.1.5 on 2023-01-15 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_information'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
